// @flow

export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_TOPNEWS_SUCCESS = 'fetch_topnews_success';

export const FETCH_DATA_ERROR1 = 'FETCH_DATA_ERROR1';
export const FETCH_DATA_REQUEST1 = 'FETCH_DATA_REQUEST1';
export const FETCH_DATA_SUCCESS1 = 'FETCH_DATA_SUCCESS1';

export const FETCH_DATA_ERROR2 = 'FETCH_DATA_ERROR2';
export const FETCH_DATA_REQUEST2 = 'FETCH_DATA_REQUEST2';
export const FETCH_DATA_SUCCESS2 = 'FETCH_DATA_SUCCESS2';

export const FETCH_DATA_ERROR3 = 'FETCH_DATA_ERROR3';
export const FETCH_DATA_REQUEST3 = 'FETCH_DATA_REQUEST3';
export const FETCH_DATA_SUCCESS3 = 'FETCH_DATA_SUCCESS3';

export const FETCH_DATA_ERROR4 = 'FETCH_DATA_ERROR4';
export const FETCH_DATA_REQUEST4 = 'FETCH_DATA_REQUEST4';
export const FETCH_DATA_SUCCESS4 = 'FETCH_DATA_SUCCESS4';

export const FETCH_TODOLIST_ERROR = 'FETCH_TODOLIST_ERROR';
export const FETCH_TODOLIST_REQUEST = 'FETCH_TODOLIST_REQUEST';
export const ADD_TODOLIST= 'ADD_TODOLIST';
export const DELETE_TODOLIST = 'DELETE_TODOLIST';
